# Generated by Django 4.2.3 on 2023-09-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeereport',
            old_name='hotel_live_fee',
            new_name='hotel_fee',
        ),
    ]
