# Generated by Django 4.1.4 on 2023-07-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
