# Generated by Django 4.2.3 on 2023-09-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_rename_hotel_live_fee_employeereport_hotel_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='oclade_tarif',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
