# Generated by Django 4.2.3 on 2023-09-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_employeereport_oclade_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='oclade_tarif',
            field=models.CharField(blank=True, default='Uzpar', max_length=100, null=True),
        ),
    ]
