# Generated by Django 4.2.3 on 2023-07-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_employeereport_month_employeereport_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeereport',
            old_name='premium',
            new_name='clasify',
        ),
        migrations.RenameField(
            model_name='employeereport',
            old_name='prepayment',
            new_name='fee_prof',
        ),
        migrations.AddField(
            model_name='employeereport',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='material_help',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='material_help_retire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='oclade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='oclade_repairment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='premium_general',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='premium_monthly',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='premium_motivation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='premium_travel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='vacation_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='vacation_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='vacation_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
