# Generated by Django 4.2.3 on 2023-09-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_employeereport_oclade_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='plastik_karta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
