# Generated by Django 4.2.3 on 2023-09-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_employeereport_plastik_karta'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='material_help_pansion_starting',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
