# Generated by Django 4.2.3 on 2023-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_alter_employeereport_material_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='material_help',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
