# Generated by Django 4.2.3 on 2023-09-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_employeereport_material_help_pansion_starting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='hospital_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='night_shift_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='nutrition_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='oclade_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='oclade_repairment_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='tariff_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='vacation_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='vacation_add_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
    ]
