# Generated by Django 4.2.3 on 2023-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_alter_employeereport_hospital_wtf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='nutrition_WTF',
            field=models.CharField(blank=True, default='nutrition', max_length=100, null=True),
        ),
    ]
