# Generated by Django 4.2.3 on 2023-07-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_rename_fee_employeereport_gsm_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeereport',
            old_name='cumilative_surcharge',
            new_name='cumulative_surcharge',
        ),
        migrations.RenameField(
            model_name='employeereport',
            old_name='harmfullness',
            new_name='harmfulness',
        ),
        migrations.RenameField(
            model_name='employeereport',
            old_name='loan_credeit_fee',
            new_name='loan_credit_fee',
        ),
        migrations.RenameField(
            model_name='employeereport',
            old_name='speacial_uniform_fee',
            new_name='special_uniform_fee',
        ),
    ]
