# Generated by Django 4.2.3 on 2023-09-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_alter_employeereport_nutrition_wtf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='Saturday_work_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='maternity_leave_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='surcharge_harm_repairment_WTF',
            field=models.CharField(blank=True, default='oklad', max_length=100, null=True),
        ),
    ]
