# Generated by Django 4.2.3 on 2023-08-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0009_rename_cumilative_surcharge_employeereport_cumulative_surcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='password',
            field=models.CharField(blank=True, default='Parol', max_length=100, null=True),
        ),
    ]
