# Generated by Django 4.2.3 on 2023-09-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_alter_employeereport_gsm_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='Saturday_work_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='avans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='hospital_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='kassa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='maternity_leave_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='night_shift_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='nutrition_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='oclade_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='oclade_repairment_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='surcharge_harm_repairment_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='tariff_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='vacation_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='vacation_add_WWF',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
